import chalk from 'chalk';
import path from 'path';
import { runWizard } from '../wizard/prompts.js';
import { installSkills } from '../../core/installer.js';
import { createDefaultConfig, saveConfig, configExists } from '../../core/config.js';
import { configureMcp, getMcpInstructions } from '../../core/mcp.js';
import { getAgentConfig } from '../../core/agents.js';

export async function initCommand(): Promise<void> {
  const projectDir = process.cwd();

  console.log(chalk.bold.blue('\n🏭 AI Factory - Project Setup\n'));

  if (await configExists(projectDir)) {
    console.log(chalk.yellow('Warning: .ai-factory.json already exists.'));
    console.log('Use "ai-factory update" to update existing skills.\n');
  }

  try {
    const answers = await runWizard(projectDir);

    console.log(chalk.dim('\nInstalling skills...\n'));

    const installedSkills = await installSkills({
      projectDir,
      skillsDir: answers.skillsDir,
      skills: answers.selectedSkills,
      stack: null, // Stack-specific skills generated by /ai-factory in Claude
      agentId: answers.agent,
    });

    const config = createDefaultConfig(answers.agent);
    config.installedSkills = installedSkills;
    config.mcp = {
      github: answers.mcpGithub,
      filesystem: answers.mcpFilesystem,
      postgres: answers.mcpPostgres,
    };

    await saveConfig(projectDir, config);

    console.log(chalk.green('✓ Configuration saved to .ai-factory.json'));

    let configuredMcp: string[] = [];
    if (answers.mcpGithub || answers.mcpFilesystem || answers.mcpPostgres || answers.mcpChromeDevtools || answers.mcpSerena) {
      configuredMcp = await configureMcp(projectDir, {
        github: answers.mcpGithub,
        filesystem: answers.mcpFilesystem,
        postgres: answers.mcpPostgres,
        chromeDevtools: answers.mcpChromeDevtools,
        serena: answers.mcpSerena,
      }, answers.agent);

      if (configuredMcp.length > 0) {
        console.log(chalk.green(`✓ MCP servers configured: ${configuredMcp.join(', ')}`));
      }
    }

    console.log(chalk.bold.green('\n✅ Setup complete!\n'));

    console.log(chalk.bold('Installed skills:'));
    for (const skill of installedSkills) {
      console.log(chalk.dim(`  - ${skill}`));
    }
    console.log('');

    console.log(chalk.dim(`Skills directory: ${path.join(projectDir, answers.skillsDir)}`));

    if (configuredMcp.length > 0) {
      console.log(chalk.bold('\nMCP Configuration:'));
      const instructions = getMcpInstructions(configuredMcp);
      for (const instruction of instructions) {
        console.log(chalk.dim(`  ${instruction}`));
      }
    }

    const agentConfig = getAgentConfig(answers.agent);
    console.log(chalk.bold('\nNext steps:'));
    console.log(chalk.dim(`  1. Open ${agentConfig.displayName} in this directory`));
    if (answers.agent === 'antigravity') {
      console.log(chalk.dim('  2. Workflows are in .agent/workflows/ (e.g. /ai-factory, /ai-factory.feature)'));
      console.log(chalk.dim('  3. Rules (guardrails) are in .agent/rules/'));
      console.log(chalk.dim('  4. Skills (knowledge) are in .agent/skills/'));
      console.log(chalk.dim('  5. MCP servers configured in .agent/settings.json'));
    } else {
      console.log(chalk.dim('  2. Run /ai-factory to analyze project and generate stack-specific skills'));
      console.log(chalk.dim('  3. Use /ai-factory.feature to start new features, /ai-factory.commit to commit'));
    }
    console.log('');

  } catch (error) {
    if ((error as Error).message?.includes('User force closed')) {
      console.log(chalk.yellow('\nSetup cancelled.'));
      return;
    }
    throw error;
  }
}
